baseURL = "https://zarnowiecki.pl/"
languageCode = "en-us"
title = "Łukasz Żarnowiecki"
theme = "hugo-theme-console"

[params]
animateStyle = "animated zoomIn fast"
description = "Personal blog"

# https://utteranc.es
[params.ghcomments]
repo = "dolohow/zarnowiecki.pl"
issueTerm = "url"
theme = "preferred-color-scheme"

[[params.navlinks]]
name = "GitHub/"
url = "https://github.com/dolohow"

[[params.navlinks]]
name = "Twitter/"
url = "https://twitter.com/puksiarz"

[[params.navlinks]]
name = "About/"
url = "about/"

[[params.navlinks]]
name = "Contact/"
url = "contact/"
