baseURL = "https://zarnowiecki.pl/"
languageCode = "en-us"
title = "Łukasz Żarnowiecki"
theme = "hugo-theme-console"

[params]
description = "Personal blog"

# https://utteranc.es
[params.ghcomments]
repo = "dolohow/zarnowiecki.pl"
issueTerm = "url"
theme = "preferred-color-scheme"

[[params.navlinks]]
name = "CV/"
url = "cv/"

[[params.navlinks]]
name = "Hire Me/"
url = "hire-me/"

[[params.navlinks]]
name = "About/"
url = "about/"